
name: Build Binaries

on:
  workflow_call:
    inputs:
      release_name:
        description: "allow setting the release name"
        default: "Latest QMK Firmware"
        required: false
        type: string
      release_tag:
        description: "allow setting the release tag"
        default: "latest"
        required: false
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    if: always() && !cancelled()
    runs-on: ubuntu-latest

    steps:
      - name: Download binaries
        if: always() && !cancelled()
        uses: actions/download-artifact@v4
        # with:
        #   name: Firmware

      - name: Generate Release
        uses: softprops/action-gh-release@v2
        if: always() && !cancelled()
        with:
          token: ${{ github.token }}
          name: ${{ inputs.release_name || 'Latest QMK Firmware' }}
          tag_name: ${{ inputs.release_tag || 'latest' }}
          fail_on_unmatched_files: false
          draft: false
          prerelease: false
          files: |
            **/*.hex
            **/*.bin
            **/*.uf2
